"""empty message

Revision ID: d2215bd1ec87
Revises: e0d162e7b7ed
Create Date: 2024-04-18 01:51:25.107274

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2215bd1ec87"
down_revision: str | None = "e0d162e7b7ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("teacher_name_constraint_unique", "teacher", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("teacher_name_constraint_unique", "teacher", type_="unique")
    # ### end Alembic commands ###
